# Usamos un servidor web profesional ultraligero llamado Nginx
FROM nginx:alpine

# Copiamos todos tus archivos web a la carpeta pública del servidor
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 (el estándar de internet)
EXPOSE 80